/*
Alephium API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.7.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alephium

import (
	"encoding/json"
)

// checks if the RevealMnemonic type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RevealMnemonic{}

// RevealMnemonic struct for RevealMnemonic
type RevealMnemonic struct {
	Password string `json:"password"`
}

// NewRevealMnemonic instantiates a new RevealMnemonic object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRevealMnemonic(password string) *RevealMnemonic {
	this := RevealMnemonic{}
	this.Password = password
	return &this
}

// NewRevealMnemonicWithDefaults instantiates a new RevealMnemonic object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRevealMnemonicWithDefaults() *RevealMnemonic {
	this := RevealMnemonic{}
	return &this
}

// GetPassword returns the Password field value
func (o *RevealMnemonic) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *RevealMnemonic) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *RevealMnemonic) SetPassword(v string) {
	o.Password = v
}

func (o RevealMnemonic) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RevealMnemonic) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["password"] = o.Password
	return toSerialize, nil
}

type NullableRevealMnemonic struct {
	value *RevealMnemonic
	isSet bool
}

func (v NullableRevealMnemonic) Get() *RevealMnemonic {
	return v.value
}

func (v *NullableRevealMnemonic) Set(val *RevealMnemonic) {
	v.value = val
	v.isSet = true
}

func (v NullableRevealMnemonic) IsSet() bool {
	return v.isSet
}

func (v *NullableRevealMnemonic) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRevealMnemonic(val *RevealMnemonic) *NullableRevealMnemonic {
	return &NullableRevealMnemonic{value: val, isSet: true}
}

func (v NullableRevealMnemonic) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRevealMnemonic) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


