/*
Alephium API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.7.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alephium

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TestContract type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TestContract{}

// TestContract struct for TestContract
type TestContract struct {
	Group *int32 `json:"group,omitempty"`
	BlockHash *string `json:"blockHash,omitempty"`
	BlockTimeStamp *int64 `json:"blockTimeStamp,omitempty"`
	TxId *string `json:"txId,omitempty"`
	Address *string `json:"address,omitempty"`
	CallerContractAddress *string `json:"callerContractAddress,omitempty"`
	Bytecode string `json:"bytecode"`
	InitialImmFields []Val `json:"initialImmFields,omitempty"`
	InitialMutFields []Val `json:"initialMutFields,omitempty"`
	InitialAsset *AssetState `json:"initialAsset,omitempty"`
	MethodIndex *int32 `json:"methodIndex,omitempty"`
	Args []Val `json:"args,omitempty"`
	ExistingContracts []ContractState `json:"existingContracts,omitempty"`
	InputAssets []TestInputAsset `json:"inputAssets,omitempty"`
	DustAmount *string `json:"dustAmount,omitempty"`
}

type _TestContract TestContract

// NewTestContract instantiates a new TestContract object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTestContract(bytecode string) *TestContract {
	this := TestContract{}
	this.Bytecode = bytecode
	return &this
}

// NewTestContractWithDefaults instantiates a new TestContract object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTestContractWithDefaults() *TestContract {
	this := TestContract{}
	return &this
}

// GetGroup returns the Group field value if set, zero value otherwise.
func (o *TestContract) GetGroup() int32 {
	if o == nil || IsNil(o.Group) {
		var ret int32
		return ret
	}
	return *o.Group
}

// GetGroupOk returns a tuple with the Group field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestContract) GetGroupOk() (*int32, bool) {
	if o == nil || IsNil(o.Group) {
		return nil, false
	}
	return o.Group, true
}

// HasGroup returns a boolean if a field has been set.
func (o *TestContract) HasGroup() bool {
	if o != nil && !IsNil(o.Group) {
		return true
	}

	return false
}

// SetGroup gets a reference to the given int32 and assigns it to the Group field.
func (o *TestContract) SetGroup(v int32) {
	o.Group = &v
}

// GetBlockHash returns the BlockHash field value if set, zero value otherwise.
func (o *TestContract) GetBlockHash() string {
	if o == nil || IsNil(o.BlockHash) {
		var ret string
		return ret
	}
	return *o.BlockHash
}

// GetBlockHashOk returns a tuple with the BlockHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestContract) GetBlockHashOk() (*string, bool) {
	if o == nil || IsNil(o.BlockHash) {
		return nil, false
	}
	return o.BlockHash, true
}

// HasBlockHash returns a boolean if a field has been set.
func (o *TestContract) HasBlockHash() bool {
	if o != nil && !IsNil(o.BlockHash) {
		return true
	}

	return false
}

// SetBlockHash gets a reference to the given string and assigns it to the BlockHash field.
func (o *TestContract) SetBlockHash(v string) {
	o.BlockHash = &v
}

// GetBlockTimeStamp returns the BlockTimeStamp field value if set, zero value otherwise.
func (o *TestContract) GetBlockTimeStamp() int64 {
	if o == nil || IsNil(o.BlockTimeStamp) {
		var ret int64
		return ret
	}
	return *o.BlockTimeStamp
}

// GetBlockTimeStampOk returns a tuple with the BlockTimeStamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestContract) GetBlockTimeStampOk() (*int64, bool) {
	if o == nil || IsNil(o.BlockTimeStamp) {
		return nil, false
	}
	return o.BlockTimeStamp, true
}

// HasBlockTimeStamp returns a boolean if a field has been set.
func (o *TestContract) HasBlockTimeStamp() bool {
	if o != nil && !IsNil(o.BlockTimeStamp) {
		return true
	}

	return false
}

// SetBlockTimeStamp gets a reference to the given int64 and assigns it to the BlockTimeStamp field.
func (o *TestContract) SetBlockTimeStamp(v int64) {
	o.BlockTimeStamp = &v
}

// GetTxId returns the TxId field value if set, zero value otherwise.
func (o *TestContract) GetTxId() string {
	if o == nil || IsNil(o.TxId) {
		var ret string
		return ret
	}
	return *o.TxId
}

// GetTxIdOk returns a tuple with the TxId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestContract) GetTxIdOk() (*string, bool) {
	if o == nil || IsNil(o.TxId) {
		return nil, false
	}
	return o.TxId, true
}

// HasTxId returns a boolean if a field has been set.
func (o *TestContract) HasTxId() bool {
	if o != nil && !IsNil(o.TxId) {
		return true
	}

	return false
}

// SetTxId gets a reference to the given string and assigns it to the TxId field.
func (o *TestContract) SetTxId(v string) {
	o.TxId = &v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *TestContract) GetAddress() string {
	if o == nil || IsNil(o.Address) {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestContract) GetAddressOk() (*string, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *TestContract) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *TestContract) SetAddress(v string) {
	o.Address = &v
}

// GetCallerContractAddress returns the CallerContractAddress field value if set, zero value otherwise.
func (o *TestContract) GetCallerContractAddress() string {
	if o == nil || IsNil(o.CallerContractAddress) {
		var ret string
		return ret
	}
	return *o.CallerContractAddress
}

// GetCallerContractAddressOk returns a tuple with the CallerContractAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestContract) GetCallerContractAddressOk() (*string, bool) {
	if o == nil || IsNil(o.CallerContractAddress) {
		return nil, false
	}
	return o.CallerContractAddress, true
}

// HasCallerContractAddress returns a boolean if a field has been set.
func (o *TestContract) HasCallerContractAddress() bool {
	if o != nil && !IsNil(o.CallerContractAddress) {
		return true
	}

	return false
}

// SetCallerContractAddress gets a reference to the given string and assigns it to the CallerContractAddress field.
func (o *TestContract) SetCallerContractAddress(v string) {
	o.CallerContractAddress = &v
}

// GetBytecode returns the Bytecode field value
func (o *TestContract) GetBytecode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Bytecode
}

// GetBytecodeOk returns a tuple with the Bytecode field value
// and a boolean to check if the value has been set.
func (o *TestContract) GetBytecodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Bytecode, true
}

// SetBytecode sets field value
func (o *TestContract) SetBytecode(v string) {
	o.Bytecode = v
}

// GetInitialImmFields returns the InitialImmFields field value if set, zero value otherwise.
func (o *TestContract) GetInitialImmFields() []Val {
	if o == nil || IsNil(o.InitialImmFields) {
		var ret []Val
		return ret
	}
	return o.InitialImmFields
}

// GetInitialImmFieldsOk returns a tuple with the InitialImmFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestContract) GetInitialImmFieldsOk() ([]Val, bool) {
	if o == nil || IsNil(o.InitialImmFields) {
		return nil, false
	}
	return o.InitialImmFields, true
}

// HasInitialImmFields returns a boolean if a field has been set.
func (o *TestContract) HasInitialImmFields() bool {
	if o != nil && !IsNil(o.InitialImmFields) {
		return true
	}

	return false
}

// SetInitialImmFields gets a reference to the given []Val and assigns it to the InitialImmFields field.
func (o *TestContract) SetInitialImmFields(v []Val) {
	o.InitialImmFields = v
}

// GetInitialMutFields returns the InitialMutFields field value if set, zero value otherwise.
func (o *TestContract) GetInitialMutFields() []Val {
	if o == nil || IsNil(o.InitialMutFields) {
		var ret []Val
		return ret
	}
	return o.InitialMutFields
}

// GetInitialMutFieldsOk returns a tuple with the InitialMutFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestContract) GetInitialMutFieldsOk() ([]Val, bool) {
	if o == nil || IsNil(o.InitialMutFields) {
		return nil, false
	}
	return o.InitialMutFields, true
}

// HasInitialMutFields returns a boolean if a field has been set.
func (o *TestContract) HasInitialMutFields() bool {
	if o != nil && !IsNil(o.InitialMutFields) {
		return true
	}

	return false
}

// SetInitialMutFields gets a reference to the given []Val and assigns it to the InitialMutFields field.
func (o *TestContract) SetInitialMutFields(v []Val) {
	o.InitialMutFields = v
}

// GetInitialAsset returns the InitialAsset field value if set, zero value otherwise.
func (o *TestContract) GetInitialAsset() AssetState {
	if o == nil || IsNil(o.InitialAsset) {
		var ret AssetState
		return ret
	}
	return *o.InitialAsset
}

// GetInitialAssetOk returns a tuple with the InitialAsset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestContract) GetInitialAssetOk() (*AssetState, bool) {
	if o == nil || IsNil(o.InitialAsset) {
		return nil, false
	}
	return o.InitialAsset, true
}

// HasInitialAsset returns a boolean if a field has been set.
func (o *TestContract) HasInitialAsset() bool {
	if o != nil && !IsNil(o.InitialAsset) {
		return true
	}

	return false
}

// SetInitialAsset gets a reference to the given AssetState and assigns it to the InitialAsset field.
func (o *TestContract) SetInitialAsset(v AssetState) {
	o.InitialAsset = &v
}

// GetMethodIndex returns the MethodIndex field value if set, zero value otherwise.
func (o *TestContract) GetMethodIndex() int32 {
	if o == nil || IsNil(o.MethodIndex) {
		var ret int32
		return ret
	}
	return *o.MethodIndex
}

// GetMethodIndexOk returns a tuple with the MethodIndex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestContract) GetMethodIndexOk() (*int32, bool) {
	if o == nil || IsNil(o.MethodIndex) {
		return nil, false
	}
	return o.MethodIndex, true
}

// HasMethodIndex returns a boolean if a field has been set.
func (o *TestContract) HasMethodIndex() bool {
	if o != nil && !IsNil(o.MethodIndex) {
		return true
	}

	return false
}

// SetMethodIndex gets a reference to the given int32 and assigns it to the MethodIndex field.
func (o *TestContract) SetMethodIndex(v int32) {
	o.MethodIndex = &v
}

// GetArgs returns the Args field value if set, zero value otherwise.
func (o *TestContract) GetArgs() []Val {
	if o == nil || IsNil(o.Args) {
		var ret []Val
		return ret
	}
	return o.Args
}

// GetArgsOk returns a tuple with the Args field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestContract) GetArgsOk() ([]Val, bool) {
	if o == nil || IsNil(o.Args) {
		return nil, false
	}
	return o.Args, true
}

// HasArgs returns a boolean if a field has been set.
func (o *TestContract) HasArgs() bool {
	if o != nil && !IsNil(o.Args) {
		return true
	}

	return false
}

// SetArgs gets a reference to the given []Val and assigns it to the Args field.
func (o *TestContract) SetArgs(v []Val) {
	o.Args = v
}

// GetExistingContracts returns the ExistingContracts field value if set, zero value otherwise.
func (o *TestContract) GetExistingContracts() []ContractState {
	if o == nil || IsNil(o.ExistingContracts) {
		var ret []ContractState
		return ret
	}
	return o.ExistingContracts
}

// GetExistingContractsOk returns a tuple with the ExistingContracts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestContract) GetExistingContractsOk() ([]ContractState, bool) {
	if o == nil || IsNil(o.ExistingContracts) {
		return nil, false
	}
	return o.ExistingContracts, true
}

// HasExistingContracts returns a boolean if a field has been set.
func (o *TestContract) HasExistingContracts() bool {
	if o != nil && !IsNil(o.ExistingContracts) {
		return true
	}

	return false
}

// SetExistingContracts gets a reference to the given []ContractState and assigns it to the ExistingContracts field.
func (o *TestContract) SetExistingContracts(v []ContractState) {
	o.ExistingContracts = v
}

// GetInputAssets returns the InputAssets field value if set, zero value otherwise.
func (o *TestContract) GetInputAssets() []TestInputAsset {
	if o == nil || IsNil(o.InputAssets) {
		var ret []TestInputAsset
		return ret
	}
	return o.InputAssets
}

// GetInputAssetsOk returns a tuple with the InputAssets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestContract) GetInputAssetsOk() ([]TestInputAsset, bool) {
	if o == nil || IsNil(o.InputAssets) {
		return nil, false
	}
	return o.InputAssets, true
}

// HasInputAssets returns a boolean if a field has been set.
func (o *TestContract) HasInputAssets() bool {
	if o != nil && !IsNil(o.InputAssets) {
		return true
	}

	return false
}

// SetInputAssets gets a reference to the given []TestInputAsset and assigns it to the InputAssets field.
func (o *TestContract) SetInputAssets(v []TestInputAsset) {
	o.InputAssets = v
}

// GetDustAmount returns the DustAmount field value if set, zero value otherwise.
func (o *TestContract) GetDustAmount() string {
	if o == nil || IsNil(o.DustAmount) {
		var ret string
		return ret
	}
	return *o.DustAmount
}

// GetDustAmountOk returns a tuple with the DustAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestContract) GetDustAmountOk() (*string, bool) {
	if o == nil || IsNil(o.DustAmount) {
		return nil, false
	}
	return o.DustAmount, true
}

// HasDustAmount returns a boolean if a field has been set.
func (o *TestContract) HasDustAmount() bool {
	if o != nil && !IsNil(o.DustAmount) {
		return true
	}

	return false
}

// SetDustAmount gets a reference to the given string and assigns it to the DustAmount field.
func (o *TestContract) SetDustAmount(v string) {
	o.DustAmount = &v
}

func (o TestContract) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TestContract) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Group) {
		toSerialize["group"] = o.Group
	}
	if !IsNil(o.BlockHash) {
		toSerialize["blockHash"] = o.BlockHash
	}
	if !IsNil(o.BlockTimeStamp) {
		toSerialize["blockTimeStamp"] = o.BlockTimeStamp
	}
	if !IsNil(o.TxId) {
		toSerialize["txId"] = o.TxId
	}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	if !IsNil(o.CallerContractAddress) {
		toSerialize["callerContractAddress"] = o.CallerContractAddress
	}
	toSerialize["bytecode"] = o.Bytecode
	if !IsNil(o.InitialImmFields) {
		toSerialize["initialImmFields"] = o.InitialImmFields
	}
	if !IsNil(o.InitialMutFields) {
		toSerialize["initialMutFields"] = o.InitialMutFields
	}
	if !IsNil(o.InitialAsset) {
		toSerialize["initialAsset"] = o.InitialAsset
	}
	if !IsNil(o.MethodIndex) {
		toSerialize["methodIndex"] = o.MethodIndex
	}
	if !IsNil(o.Args) {
		toSerialize["args"] = o.Args
	}
	if !IsNil(o.ExistingContracts) {
		toSerialize["existingContracts"] = o.ExistingContracts
	}
	if !IsNil(o.InputAssets) {
		toSerialize["inputAssets"] = o.InputAssets
	}
	if !IsNil(o.DustAmount) {
		toSerialize["dustAmount"] = o.DustAmount
	}
	return toSerialize, nil
}

func (o *TestContract) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"bytecode",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTestContract := _TestContract{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTestContract)

	if err != nil {
		return err
	}

	*o = TestContract(varTestContract)

	return err
}

type NullableTestContract struct {
	value *TestContract
	isSet bool
}

func (v NullableTestContract) Get() *TestContract {
	return v.value
}

func (v *NullableTestContract) Set(val *TestContract) {
	v.value = val
	v.isSet = true
}

func (v NullableTestContract) IsSet() bool {
	return v.isSet
}

func (v *NullableTestContract) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTestContract(val *TestContract) *NullableTestContract {
	return &NullableTestContract{value: val, isSet: true}
}

func (v NullableTestContract) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTestContract) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


