/*
Alephium API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.5.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alephium

import (
	"encoding/json"
)

// checks if the Sign type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Sign{}

// Sign struct for Sign
type Sign struct {
	Data string `json:"data"`
}

// NewSign instantiates a new Sign object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSign(data string) *Sign {
	this := Sign{}
	this.Data = data
	return &this
}

// NewSignWithDefaults instantiates a new Sign object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSignWithDefaults() *Sign {
	this := Sign{}
	return &this
}

// GetData returns the Data field value
func (o *Sign) GetData() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *Sign) GetDataOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *Sign) SetData(v string) {
	o.Data = v
}

func (o Sign) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Sign) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

type NullableSign struct {
	value *Sign
	isSet bool
}

func (v NullableSign) Get() *Sign {
	return v.value
}

func (v *NullableSign) Set(val *Sign) {
	v.value = val
	v.isSet = true
}

func (v NullableSign) IsSet() bool {
	return v.isSet
}

func (v *NullableSign) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSign(val *Sign) *NullableSign {
	return &NullableSign{value: val, isSet: true}
}

func (v NullableSign) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSign) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


