/*
Alephium API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.7.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alephium

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BuildChainedDeployContractTx type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BuildChainedDeployContractTx{}

// BuildChainedDeployContractTx struct for BuildChainedDeployContractTx
type BuildChainedDeployContractTx struct {
	Value BuildDeployContractTx `json:"value"`
	Type string `json:"type"`
}

type _BuildChainedDeployContractTx BuildChainedDeployContractTx

// NewBuildChainedDeployContractTx instantiates a new BuildChainedDeployContractTx object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBuildChainedDeployContractTx(value BuildDeployContractTx, type_ string) *BuildChainedDeployContractTx {
	this := BuildChainedDeployContractTx{}
	this.Value = value
	this.Type = type_
	return &this
}

// NewBuildChainedDeployContractTxWithDefaults instantiates a new BuildChainedDeployContractTx object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBuildChainedDeployContractTxWithDefaults() *BuildChainedDeployContractTx {
	this := BuildChainedDeployContractTx{}
	return &this
}

// GetValue returns the Value field value
func (o *BuildChainedDeployContractTx) GetValue() BuildDeployContractTx {
	if o == nil {
		var ret BuildDeployContractTx
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *BuildChainedDeployContractTx) GetValueOk() (*BuildDeployContractTx, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *BuildChainedDeployContractTx) SetValue(v BuildDeployContractTx) {
	o.Value = v
}

// GetType returns the Type field value
func (o *BuildChainedDeployContractTx) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *BuildChainedDeployContractTx) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *BuildChainedDeployContractTx) SetType(v string) {
	o.Type = v
}

func (o BuildChainedDeployContractTx) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BuildChainedDeployContractTx) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["value"] = o.Value
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *BuildChainedDeployContractTx) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"value",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBuildChainedDeployContractTx := _BuildChainedDeployContractTx{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBuildChainedDeployContractTx)

	if err != nil {
		return err
	}

	*o = BuildChainedDeployContractTx(varBuildChainedDeployContractTx)

	return err
}

type NullableBuildChainedDeployContractTx struct {
	value *BuildChainedDeployContractTx
	isSet bool
}

func (v NullableBuildChainedDeployContractTx) Get() *BuildChainedDeployContractTx {
	return v.value
}

func (v *NullableBuildChainedDeployContractTx) Set(val *BuildChainedDeployContractTx) {
	v.value = val
	v.isSet = true
}

func (v NullableBuildChainedDeployContractTx) IsSet() bool {
	return v.isSet
}

func (v *NullableBuildChainedDeployContractTx) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBuildChainedDeployContractTx(val *BuildChainedDeployContractTx) *NullableBuildChainedDeployContractTx {
	return &NullableBuildChainedDeployContractTx{value: val, isSet: true}
}

func (v NullableBuildChainedDeployContractTx) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBuildChainedDeployContractTx) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


