/*
Alephium API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alephium

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RichBlocksAndEventsPerTimeStampRange type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RichBlocksAndEventsPerTimeStampRange{}

// RichBlocksAndEventsPerTimeStampRange struct for RichBlocksAndEventsPerTimeStampRange
type RichBlocksAndEventsPerTimeStampRange struct {
	BlocksAndEvents [][]RichBlockAndEvents `json:"blocksAndEvents"`
}

type _RichBlocksAndEventsPerTimeStampRange RichBlocksAndEventsPerTimeStampRange

// NewRichBlocksAndEventsPerTimeStampRange instantiates a new RichBlocksAndEventsPerTimeStampRange object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRichBlocksAndEventsPerTimeStampRange(blocksAndEvents [][]RichBlockAndEvents) *RichBlocksAndEventsPerTimeStampRange {
	this := RichBlocksAndEventsPerTimeStampRange{}
	this.BlocksAndEvents = blocksAndEvents
	return &this
}

// NewRichBlocksAndEventsPerTimeStampRangeWithDefaults instantiates a new RichBlocksAndEventsPerTimeStampRange object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRichBlocksAndEventsPerTimeStampRangeWithDefaults() *RichBlocksAndEventsPerTimeStampRange {
	this := RichBlocksAndEventsPerTimeStampRange{}
	return &this
}

// GetBlocksAndEvents returns the BlocksAndEvents field value
func (o *RichBlocksAndEventsPerTimeStampRange) GetBlocksAndEvents() [][]RichBlockAndEvents {
	if o == nil {
		var ret [][]RichBlockAndEvents
		return ret
	}

	return o.BlocksAndEvents
}

// GetBlocksAndEventsOk returns a tuple with the BlocksAndEvents field value
// and a boolean to check if the value has been set.
func (o *RichBlocksAndEventsPerTimeStampRange) GetBlocksAndEventsOk() ([][]RichBlockAndEvents, bool) {
	if o == nil {
		return nil, false
	}
	return o.BlocksAndEvents, true
}

// SetBlocksAndEvents sets field value
func (o *RichBlocksAndEventsPerTimeStampRange) SetBlocksAndEvents(v [][]RichBlockAndEvents) {
	o.BlocksAndEvents = v
}

func (o RichBlocksAndEventsPerTimeStampRange) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RichBlocksAndEventsPerTimeStampRange) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["blocksAndEvents"] = o.BlocksAndEvents
	return toSerialize, nil
}

func (o *RichBlocksAndEventsPerTimeStampRange) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"blocksAndEvents",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRichBlocksAndEventsPerTimeStampRange := _RichBlocksAndEventsPerTimeStampRange{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRichBlocksAndEventsPerTimeStampRange)

	if err != nil {
		return err
	}

	*o = RichBlocksAndEventsPerTimeStampRange(varRichBlocksAndEventsPerTimeStampRange)

	return err
}

type NullableRichBlocksAndEventsPerTimeStampRange struct {
	value *RichBlocksAndEventsPerTimeStampRange
	isSet bool
}

func (v NullableRichBlocksAndEventsPerTimeStampRange) Get() *RichBlocksAndEventsPerTimeStampRange {
	return v.value
}

func (v *NullableRichBlocksAndEventsPerTimeStampRange) Set(val *RichBlocksAndEventsPerTimeStampRange) {
	v.value = val
	v.isSet = true
}

func (v NullableRichBlocksAndEventsPerTimeStampRange) IsSet() bool {
	return v.isSet
}

func (v *NullableRichBlocksAndEventsPerTimeStampRange) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRichBlocksAndEventsPerTimeStampRange(val *RichBlocksAndEventsPerTimeStampRange) *NullableRichBlocksAndEventsPerTimeStampRange {
	return &NullableRichBlocksAndEventsPerTimeStampRange{value: val, isSet: true}
}

func (v NullableRichBlocksAndEventsPerTimeStampRange) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRichBlocksAndEventsPerTimeStampRange) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


