/*
Alephium API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alephium

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RichBlockAndEvents type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RichBlockAndEvents{}

// RichBlockAndEvents struct for RichBlockAndEvents
type RichBlockAndEvents struct {
	Block RichBlockEntry `json:"block"`
	Events []ContractEventByBlockHash `json:"events"`
}

type _RichBlockAndEvents RichBlockAndEvents

// NewRichBlockAndEvents instantiates a new RichBlockAndEvents object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRichBlockAndEvents(block RichBlockEntry, events []ContractEventByBlockHash) *RichBlockAndEvents {
	this := RichBlockAndEvents{}
	this.Block = block
	this.Events = events
	return &this
}

// NewRichBlockAndEventsWithDefaults instantiates a new RichBlockAndEvents object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRichBlockAndEventsWithDefaults() *RichBlockAndEvents {
	this := RichBlockAndEvents{}
	return &this
}

// GetBlock returns the Block field value
func (o *RichBlockAndEvents) GetBlock() RichBlockEntry {
	if o == nil {
		var ret RichBlockEntry
		return ret
	}

	return o.Block
}

// GetBlockOk returns a tuple with the Block field value
// and a boolean to check if the value has been set.
func (o *RichBlockAndEvents) GetBlockOk() (*RichBlockEntry, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Block, true
}

// SetBlock sets field value
func (o *RichBlockAndEvents) SetBlock(v RichBlockEntry) {
	o.Block = v
}

// GetEvents returns the Events field value
func (o *RichBlockAndEvents) GetEvents() []ContractEventByBlockHash {
	if o == nil {
		var ret []ContractEventByBlockHash
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
func (o *RichBlockAndEvents) GetEventsOk() ([]ContractEventByBlockHash, bool) {
	if o == nil {
		return nil, false
	}
	return o.Events, true
}

// SetEvents sets field value
func (o *RichBlockAndEvents) SetEvents(v []ContractEventByBlockHash) {
	o.Events = v
}

func (o RichBlockAndEvents) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RichBlockAndEvents) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["block"] = o.Block
	toSerialize["events"] = o.Events
	return toSerialize, nil
}

func (o *RichBlockAndEvents) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"block",
		"events",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRichBlockAndEvents := _RichBlockAndEvents{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRichBlockAndEvents)

	if err != nil {
		return err
	}

	*o = RichBlockAndEvents(varRichBlockAndEvents)

	return err
}

type NullableRichBlockAndEvents struct {
	value *RichBlockAndEvents
	isSet bool
}

func (v NullableRichBlockAndEvents) Get() *RichBlockAndEvents {
	return v.value
}

func (v *NullableRichBlockAndEvents) Set(val *RichBlockAndEvents) {
	v.value = val
	v.isSet = true
}

func (v NullableRichBlockAndEvents) IsSet() bool {
	return v.isSet
}

func (v *NullableRichBlockAndEvents) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRichBlockAndEvents(val *RichBlockAndEvents) *NullableRichBlockAndEvents {
	return &NullableRichBlockAndEvents{value: val, isSet: true}
}

func (v NullableRichBlockAndEvents) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRichBlockAndEvents) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


