/*
Alephium API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alephium

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BuildChainedTransferTx type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BuildChainedTransferTx{}

// BuildChainedTransferTx struct for BuildChainedTransferTx
type BuildChainedTransferTx struct {
	Value BuildTransferTx `json:"value"`
	Type string `json:"type"`
}

type _BuildChainedTransferTx BuildChainedTransferTx

// NewBuildChainedTransferTx instantiates a new BuildChainedTransferTx object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBuildChainedTransferTx(value BuildTransferTx, type_ string) *BuildChainedTransferTx {
	this := BuildChainedTransferTx{}
	this.Value = value
	this.Type = type_
	return &this
}

// NewBuildChainedTransferTxWithDefaults instantiates a new BuildChainedTransferTx object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBuildChainedTransferTxWithDefaults() *BuildChainedTransferTx {
	this := BuildChainedTransferTx{}
	return &this
}

// GetValue returns the Value field value
func (o *BuildChainedTransferTx) GetValue() BuildTransferTx {
	if o == nil {
		var ret BuildTransferTx
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *BuildChainedTransferTx) GetValueOk() (*BuildTransferTx, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *BuildChainedTransferTx) SetValue(v BuildTransferTx) {
	o.Value = v
}

// GetType returns the Type field value
func (o *BuildChainedTransferTx) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *BuildChainedTransferTx) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *BuildChainedTransferTx) SetType(v string) {
	o.Type = v
}

func (o BuildChainedTransferTx) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BuildChainedTransferTx) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["value"] = o.Value
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *BuildChainedTransferTx) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"value",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBuildChainedTransferTx := _BuildChainedTransferTx{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBuildChainedTransferTx)

	if err != nil {
		return err
	}

	*o = BuildChainedTransferTx(varBuildChainedTransferTx)

	return err
}

type NullableBuildChainedTransferTx struct {
	value *BuildChainedTransferTx
	isSet bool
}

func (v NullableBuildChainedTransferTx) Get() *BuildChainedTransferTx {
	return v.value
}

func (v *NullableBuildChainedTransferTx) Set(val *BuildChainedTransferTx) {
	v.value = val
	v.isSet = true
}

func (v NullableBuildChainedTransferTx) IsSet() bool {
	return v.isSet
}

func (v *NullableBuildChainedTransferTx) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBuildChainedTransferTx(val *BuildChainedTransferTx) *NullableBuildChainedTransferTx {
	return &NullableBuildChainedTransferTx{value: val, isSet: true}
}

func (v NullableBuildChainedTransferTx) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBuildChainedTransferTx) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


