/*
Alephium API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.7.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alephium

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// BuildChainedTx - struct for BuildChainedTx
type BuildChainedTx struct {
	BuildChainedDeployContractTx *BuildChainedDeployContractTx
	BuildChainedExecuteScriptTx  *BuildChainedExecuteScriptTx
	BuildChainedTransferTx       *BuildChainedTransferTx
}

// BuildChainedDeployContractTxAsBuildChainedTx is a convenience function that returns BuildChainedDeployContractTx wrapped in BuildChainedTx
func BuildChainedDeployContractTxAsBuildChainedTx(v *BuildChainedDeployContractTx) BuildChainedTx {
	return BuildChainedTx{
		BuildChainedDeployContractTx: v,
	}
}

// BuildChainedExecuteScriptTxAsBuildChainedTx is a convenience function that returns BuildChainedExecuteScriptTx wrapped in BuildChainedTx
func BuildChainedExecuteScriptTxAsBuildChainedTx(v *BuildChainedExecuteScriptTx) BuildChainedTx {
	return BuildChainedTx{
		BuildChainedExecuteScriptTx: v,
	}
}

// BuildChainedTransferTxAsBuildChainedTx is a convenience function that returns BuildChainedTransferTx wrapped in BuildChainedTx
func BuildChainedTransferTxAsBuildChainedTx(v *BuildChainedTransferTx) BuildChainedTx {
	return BuildChainedTx{
		BuildChainedTransferTx: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *BuildChainedTx) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into BuildChainedDeployContractTx
	err = newStrictDecoder(data).Decode(&dst.BuildChainedDeployContractTx)
	if err == nil {
		if dst.BuildChainedDeployContractTx == nil || dst.BuildChainedDeployContractTx.Type != "DeployContract" { // not the right type
			dst.BuildChainedDeployContractTx = nil
		} else {
			if err = validator.Validate(dst.BuildChainedDeployContractTx); err != nil {
				dst.BuildChainedDeployContractTx = nil
			} else {
				match++
			}
		}
	} else {
		dst.BuildChainedDeployContractTx = nil
	}

	// try to unmarshal data into BuildChainedExecuteScriptTx
	err = newStrictDecoder(data).Decode(&dst.BuildChainedExecuteScriptTx)
	if err == nil {
		if dst.BuildChainedExecuteScriptTx == nil || dst.BuildChainedExecuteScriptTx.Type != "ExecuteScript" { // not the right type
			dst.BuildChainedExecuteScriptTx = nil
		} else {
			if err = validator.Validate(dst.BuildChainedExecuteScriptTx); err != nil {
				dst.BuildChainedExecuteScriptTx = nil
			} else {
				match++
			}
		}
	} else {
		dst.BuildChainedExecuteScriptTx = nil
	}

	// try to unmarshal data into BuildChainedTransferTx
	err = newStrictDecoder(data).Decode(&dst.BuildChainedTransferTx)
	if err == nil {
		if dst.BuildChainedTransferTx == nil || dst.BuildChainedTransferTx.Type != "Transfer" { // not the right type
			dst.BuildChainedTransferTx = nil
		} else {
			if err = validator.Validate(dst.BuildChainedTransferTx); err != nil {
				dst.BuildChainedTransferTx = nil
			} else {
				match++
			}
		}
	} else {
		dst.BuildChainedTransferTx = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.BuildChainedDeployContractTx = nil
		dst.BuildChainedExecuteScriptTx = nil
		dst.BuildChainedTransferTx = nil

		return fmt.Errorf("data matches more than one schema in oneOf(BuildChainedTx)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(BuildChainedTx)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src BuildChainedTx) MarshalJSON() ([]byte, error) {
	if src.BuildChainedDeployContractTx != nil {
		return json.Marshal(&src.BuildChainedDeployContractTx)
	}

	if src.BuildChainedExecuteScriptTx != nil {
		return json.Marshal(&src.BuildChainedExecuteScriptTx)
	}

	if src.BuildChainedTransferTx != nil {
		return json.Marshal(&src.BuildChainedTransferTx)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *BuildChainedTx) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.BuildChainedDeployContractTx != nil {
		return obj.BuildChainedDeployContractTx
	}

	if obj.BuildChainedExecuteScriptTx != nil {
		return obj.BuildChainedExecuteScriptTx
	}

	if obj.BuildChainedTransferTx != nil {
		return obj.BuildChainedTransferTx
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj BuildChainedTx) GetActualInstanceValue() interface{} {
	if obj.BuildChainedDeployContractTx != nil {
		return *obj.BuildChainedDeployContractTx
	}

	if obj.BuildChainedExecuteScriptTx != nil {
		return *obj.BuildChainedExecuteScriptTx
	}

	if obj.BuildChainedTransferTx != nil {
		return *obj.BuildChainedTransferTx
	}

	// all schemas are nil
	return nil
}

type NullableBuildChainedTx struct {
	value *BuildChainedTx
	isSet bool
}

func (v NullableBuildChainedTx) Get() *BuildChainedTx {
	return v.value
}

func (v *NullableBuildChainedTx) Set(val *BuildChainedTx) {
	v.value = val
	v.isSet = true
}

func (v NullableBuildChainedTx) IsSet() bool {
	return v.isSet
}

func (v *NullableBuildChainedTx) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBuildChainedTx(val *BuildChainedTx) *NullableBuildChainedTx {
	return &NullableBuildChainedTx{value: val, isSet: true}
}

func (v NullableBuildChainedTx) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBuildChainedTx) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
