/*
Alephium API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alephium

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GatewayTimeout type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GatewayTimeout{}

// GatewayTimeout struct for GatewayTimeout
type GatewayTimeout struct {
	Detail string `json:"detail"`
}

type _GatewayTimeout GatewayTimeout

// NewGatewayTimeout instantiates a new GatewayTimeout object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGatewayTimeout(detail string) *GatewayTimeout {
	this := GatewayTimeout{}
	this.Detail = detail
	return &this
}

// NewGatewayTimeoutWithDefaults instantiates a new GatewayTimeout object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGatewayTimeoutWithDefaults() *GatewayTimeout {
	this := GatewayTimeout{}
	return &this
}

// GetDetail returns the Detail field value
func (o *GatewayTimeout) GetDetail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Detail
}

// GetDetailOk returns a tuple with the Detail field value
// and a boolean to check if the value has been set.
func (o *GatewayTimeout) GetDetailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Detail, true
}

// SetDetail sets field value
func (o *GatewayTimeout) SetDetail(v string) {
	o.Detail = v
}

func (o GatewayTimeout) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GatewayTimeout) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["detail"] = o.Detail
	return toSerialize, nil
}

func (o *GatewayTimeout) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"detail",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGatewayTimeout := _GatewayTimeout{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGatewayTimeout)

	if err != nil {
		return err
	}

	*o = GatewayTimeout(varGatewayTimeout)

	return err
}

type NullableGatewayTimeout struct {
	value *GatewayTimeout
	isSet bool
}

func (v NullableGatewayTimeout) Get() *GatewayTimeout {
	return v.value
}

func (v *NullableGatewayTimeout) Set(val *GatewayTimeout) {
	v.value = val
	v.isSet = true
}

func (v NullableGatewayTimeout) IsSet() bool {
	return v.isSet
}

func (v *NullableGatewayTimeout) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGatewayTimeout(val *GatewayTimeout) *NullableGatewayTimeout {
	return &NullableGatewayTimeout{value: val, isSet: true}
}

func (v NullableGatewayTimeout) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGatewayTimeout) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


