/*
Alephium API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.7.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alephium

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Ban type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Ban{}

// Ban struct for Ban
type Ban struct {
	Peers []string `json:"peers"`
	Type string `json:"type"`
}

type _Ban Ban

// NewBan instantiates a new Ban object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBan(peers []string, type_ string) *Ban {
	this := Ban{}
	this.Peers = peers
	this.Type = type_
	return &this
}

// NewBanWithDefaults instantiates a new Ban object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBanWithDefaults() *Ban {
	this := Ban{}
	return &this
}

// GetPeers returns the Peers field value
func (o *Ban) GetPeers() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Peers
}

// GetPeersOk returns a tuple with the Peers field value
// and a boolean to check if the value has been set.
func (o *Ban) GetPeersOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Peers, true
}

// SetPeers sets field value
func (o *Ban) SetPeers(v []string) {
	o.Peers = v
}

// GetType returns the Type field value
func (o *Ban) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *Ban) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *Ban) SetType(v string) {
	o.Type = v
}

func (o Ban) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Ban) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["peers"] = o.Peers
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *Ban) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"peers",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBan := _Ban{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBan)

	if err != nil {
		return err
	}

	*o = Ban(varBan)

	return err
}

type NullableBan struct {
	value *Ban
	isSet bool
}

func (v NullableBan) Get() *Ban {
	return v.value
}

func (v *NullableBan) Set(val *Ban) {
	v.value = val
	v.isSet = true
}

func (v NullableBan) IsSet() bool {
	return v.isSet
}

func (v *NullableBan) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBan(val *Ban) *NullableBan {
	return &NullableBan{value: val, isSet: true}
}

func (v NullableBan) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBan) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


