/*
Alephium API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.7.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alephium

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TargetToHashrate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TargetToHashrate{}

// TargetToHashrate struct for TargetToHashrate
type TargetToHashrate struct {
	Target string `json:"target"`
}

type _TargetToHashrate TargetToHashrate

// NewTargetToHashrate instantiates a new TargetToHashrate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTargetToHashrate(target string) *TargetToHashrate {
	this := TargetToHashrate{}
	this.Target = target
	return &this
}

// NewTargetToHashrateWithDefaults instantiates a new TargetToHashrate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTargetToHashrateWithDefaults() *TargetToHashrate {
	this := TargetToHashrate{}
	return &this
}

// GetTarget returns the Target field value
func (o *TargetToHashrate) GetTarget() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Target
}

// GetTargetOk returns a tuple with the Target field value
// and a boolean to check if the value has been set.
func (o *TargetToHashrate) GetTargetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Target, true
}

// SetTarget sets field value
func (o *TargetToHashrate) SetTarget(v string) {
	o.Target = v
}

func (o TargetToHashrate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TargetToHashrate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["target"] = o.Target
	return toSerialize, nil
}

func (o *TargetToHashrate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"target",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTargetToHashrate := _TargetToHashrate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTargetToHashrate)

	if err != nil {
		return err
	}

	*o = TargetToHashrate(varTargetToHashrate)

	return err
}

type NullableTargetToHashrate struct {
	value *TargetToHashrate
	isSet bool
}

func (v NullableTargetToHashrate) Get() *TargetToHashrate {
	return v.value
}

func (v *NullableTargetToHashrate) Set(val *TargetToHashrate) {
	v.value = val
	v.isSet = true
}

func (v NullableTargetToHashrate) IsSet() bool {
	return v.isSet
}

func (v *NullableTargetToHashrate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTargetToHashrate(val *TargetToHashrate) *NullableTargetToHashrate {
	return &NullableTargetToHashrate{value: val, isSet: true}
}

func (v NullableTargetToHashrate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTargetToHashrate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


