/*
Alephium API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.5.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alephium

import (
	"encoding/json"
)

// checks if the BuildDeployContractTx type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BuildDeployContractTx{}

// BuildDeployContractTx struct for BuildDeployContractTx
type BuildDeployContractTx struct {
	FromPublicKey string `json:"fromPublicKey"`
	FromPublicKeyType *string `json:"fromPublicKeyType,omitempty"`
	Bytecode string `json:"bytecode"`
	InitialAttoAlphAmount *string `json:"initialAttoAlphAmount,omitempty"`
	InitialTokenAmounts []Token `json:"initialTokenAmounts,omitempty"`
	IssueTokenAmount *string `json:"issueTokenAmount,omitempty"`
	GasAmount *int32 `json:"gasAmount,omitempty"`
	GasPrice *string `json:"gasPrice,omitempty"`
	TargetBlockHash *string `json:"targetBlockHash,omitempty"`
}

// NewBuildDeployContractTx instantiates a new BuildDeployContractTx object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBuildDeployContractTx(fromPublicKey string, bytecode string) *BuildDeployContractTx {
	this := BuildDeployContractTx{}
	this.FromPublicKey = fromPublicKey
	this.Bytecode = bytecode
	return &this
}

// NewBuildDeployContractTxWithDefaults instantiates a new BuildDeployContractTx object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBuildDeployContractTxWithDefaults() *BuildDeployContractTx {
	this := BuildDeployContractTx{}
	return &this
}

// GetFromPublicKey returns the FromPublicKey field value
func (o *BuildDeployContractTx) GetFromPublicKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FromPublicKey
}

// GetFromPublicKeyOk returns a tuple with the FromPublicKey field value
// and a boolean to check if the value has been set.
func (o *BuildDeployContractTx) GetFromPublicKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FromPublicKey, true
}

// SetFromPublicKey sets field value
func (o *BuildDeployContractTx) SetFromPublicKey(v string) {
	o.FromPublicKey = v
}

// GetFromPublicKeyType returns the FromPublicKeyType field value if set, zero value otherwise.
func (o *BuildDeployContractTx) GetFromPublicKeyType() string {
	if o == nil || isNil(o.FromPublicKeyType) {
		var ret string
		return ret
	}
	return *o.FromPublicKeyType
}

// GetFromPublicKeyTypeOk returns a tuple with the FromPublicKeyType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuildDeployContractTx) GetFromPublicKeyTypeOk() (*string, bool) {
	if o == nil || isNil(o.FromPublicKeyType) {
		return nil, false
	}
	return o.FromPublicKeyType, true
}

// HasFromPublicKeyType returns a boolean if a field has been set.
func (o *BuildDeployContractTx) HasFromPublicKeyType() bool {
	if o != nil && !isNil(o.FromPublicKeyType) {
		return true
	}

	return false
}

// SetFromPublicKeyType gets a reference to the given string and assigns it to the FromPublicKeyType field.
func (o *BuildDeployContractTx) SetFromPublicKeyType(v string) {
	o.FromPublicKeyType = &v
}

// GetBytecode returns the Bytecode field value
func (o *BuildDeployContractTx) GetBytecode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Bytecode
}

// GetBytecodeOk returns a tuple with the Bytecode field value
// and a boolean to check if the value has been set.
func (o *BuildDeployContractTx) GetBytecodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Bytecode, true
}

// SetBytecode sets field value
func (o *BuildDeployContractTx) SetBytecode(v string) {
	o.Bytecode = v
}

// GetInitialAttoAlphAmount returns the InitialAttoAlphAmount field value if set, zero value otherwise.
func (o *BuildDeployContractTx) GetInitialAttoAlphAmount() string {
	if o == nil || isNil(o.InitialAttoAlphAmount) {
		var ret string
		return ret
	}
	return *o.InitialAttoAlphAmount
}

// GetInitialAttoAlphAmountOk returns a tuple with the InitialAttoAlphAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuildDeployContractTx) GetInitialAttoAlphAmountOk() (*string, bool) {
	if o == nil || isNil(o.InitialAttoAlphAmount) {
		return nil, false
	}
	return o.InitialAttoAlphAmount, true
}

// HasInitialAttoAlphAmount returns a boolean if a field has been set.
func (o *BuildDeployContractTx) HasInitialAttoAlphAmount() bool {
	if o != nil && !isNil(o.InitialAttoAlphAmount) {
		return true
	}

	return false
}

// SetInitialAttoAlphAmount gets a reference to the given string and assigns it to the InitialAttoAlphAmount field.
func (o *BuildDeployContractTx) SetInitialAttoAlphAmount(v string) {
	o.InitialAttoAlphAmount = &v
}

// GetInitialTokenAmounts returns the InitialTokenAmounts field value if set, zero value otherwise.
func (o *BuildDeployContractTx) GetInitialTokenAmounts() []Token {
	if o == nil || isNil(o.InitialTokenAmounts) {
		var ret []Token
		return ret
	}
	return o.InitialTokenAmounts
}

// GetInitialTokenAmountsOk returns a tuple with the InitialTokenAmounts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuildDeployContractTx) GetInitialTokenAmountsOk() ([]Token, bool) {
	if o == nil || isNil(o.InitialTokenAmounts) {
		return nil, false
	}
	return o.InitialTokenAmounts, true
}

// HasInitialTokenAmounts returns a boolean if a field has been set.
func (o *BuildDeployContractTx) HasInitialTokenAmounts() bool {
	if o != nil && !isNil(o.InitialTokenAmounts) {
		return true
	}

	return false
}

// SetInitialTokenAmounts gets a reference to the given []Token and assigns it to the InitialTokenAmounts field.
func (o *BuildDeployContractTx) SetInitialTokenAmounts(v []Token) {
	o.InitialTokenAmounts = v
}

// GetIssueTokenAmount returns the IssueTokenAmount field value if set, zero value otherwise.
func (o *BuildDeployContractTx) GetIssueTokenAmount() string {
	if o == nil || isNil(o.IssueTokenAmount) {
		var ret string
		return ret
	}
	return *o.IssueTokenAmount
}

// GetIssueTokenAmountOk returns a tuple with the IssueTokenAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuildDeployContractTx) GetIssueTokenAmountOk() (*string, bool) {
	if o == nil || isNil(o.IssueTokenAmount) {
		return nil, false
	}
	return o.IssueTokenAmount, true
}

// HasIssueTokenAmount returns a boolean if a field has been set.
func (o *BuildDeployContractTx) HasIssueTokenAmount() bool {
	if o != nil && !isNil(o.IssueTokenAmount) {
		return true
	}

	return false
}

// SetIssueTokenAmount gets a reference to the given string and assigns it to the IssueTokenAmount field.
func (o *BuildDeployContractTx) SetIssueTokenAmount(v string) {
	o.IssueTokenAmount = &v
}

// GetGasAmount returns the GasAmount field value if set, zero value otherwise.
func (o *BuildDeployContractTx) GetGasAmount() int32 {
	if o == nil || isNil(o.GasAmount) {
		var ret int32
		return ret
	}
	return *o.GasAmount
}

// GetGasAmountOk returns a tuple with the GasAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuildDeployContractTx) GetGasAmountOk() (*int32, bool) {
	if o == nil || isNil(o.GasAmount) {
		return nil, false
	}
	return o.GasAmount, true
}

// HasGasAmount returns a boolean if a field has been set.
func (o *BuildDeployContractTx) HasGasAmount() bool {
	if o != nil && !isNil(o.GasAmount) {
		return true
	}

	return false
}

// SetGasAmount gets a reference to the given int32 and assigns it to the GasAmount field.
func (o *BuildDeployContractTx) SetGasAmount(v int32) {
	o.GasAmount = &v
}

// GetGasPrice returns the GasPrice field value if set, zero value otherwise.
func (o *BuildDeployContractTx) GetGasPrice() string {
	if o == nil || isNil(o.GasPrice) {
		var ret string
		return ret
	}
	return *o.GasPrice
}

// GetGasPriceOk returns a tuple with the GasPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuildDeployContractTx) GetGasPriceOk() (*string, bool) {
	if o == nil || isNil(o.GasPrice) {
		return nil, false
	}
	return o.GasPrice, true
}

// HasGasPrice returns a boolean if a field has been set.
func (o *BuildDeployContractTx) HasGasPrice() bool {
	if o != nil && !isNil(o.GasPrice) {
		return true
	}

	return false
}

// SetGasPrice gets a reference to the given string and assigns it to the GasPrice field.
func (o *BuildDeployContractTx) SetGasPrice(v string) {
	o.GasPrice = &v
}

// GetTargetBlockHash returns the TargetBlockHash field value if set, zero value otherwise.
func (o *BuildDeployContractTx) GetTargetBlockHash() string {
	if o == nil || isNil(o.TargetBlockHash) {
		var ret string
		return ret
	}
	return *o.TargetBlockHash
}

// GetTargetBlockHashOk returns a tuple with the TargetBlockHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuildDeployContractTx) GetTargetBlockHashOk() (*string, bool) {
	if o == nil || isNil(o.TargetBlockHash) {
		return nil, false
	}
	return o.TargetBlockHash, true
}

// HasTargetBlockHash returns a boolean if a field has been set.
func (o *BuildDeployContractTx) HasTargetBlockHash() bool {
	if o != nil && !isNil(o.TargetBlockHash) {
		return true
	}

	return false
}

// SetTargetBlockHash gets a reference to the given string and assigns it to the TargetBlockHash field.
func (o *BuildDeployContractTx) SetTargetBlockHash(v string) {
	o.TargetBlockHash = &v
}

func (o BuildDeployContractTx) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BuildDeployContractTx) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["fromPublicKey"] = o.FromPublicKey
	if !isNil(o.FromPublicKeyType) {
		toSerialize["fromPublicKeyType"] = o.FromPublicKeyType
	}
	toSerialize["bytecode"] = o.Bytecode
	if !isNil(o.InitialAttoAlphAmount) {
		toSerialize["initialAttoAlphAmount"] = o.InitialAttoAlphAmount
	}
	if !isNil(o.InitialTokenAmounts) {
		toSerialize["initialTokenAmounts"] = o.InitialTokenAmounts
	}
	if !isNil(o.IssueTokenAmount) {
		toSerialize["issueTokenAmount"] = o.IssueTokenAmount
	}
	if !isNil(o.GasAmount) {
		toSerialize["gasAmount"] = o.GasAmount
	}
	if !isNil(o.GasPrice) {
		toSerialize["gasPrice"] = o.GasPrice
	}
	if !isNil(o.TargetBlockHash) {
		toSerialize["targetBlockHash"] = o.TargetBlockHash
	}
	return toSerialize, nil
}

type NullableBuildDeployContractTx struct {
	value *BuildDeployContractTx
	isSet bool
}

func (v NullableBuildDeployContractTx) Get() *BuildDeployContractTx {
	return v.value
}

func (v *NullableBuildDeployContractTx) Set(val *BuildDeployContractTx) {
	v.value = val
	v.isSet = true
}

func (v NullableBuildDeployContractTx) IsSet() bool {
	return v.isSet
}

func (v *NullableBuildDeployContractTx) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBuildDeployContractTx(val *BuildDeployContractTx) *NullableBuildDeployContractTx {
	return &NullableBuildDeployContractTx{value: val, isSet: true}
}

func (v NullableBuildDeployContractTx) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBuildDeployContractTx) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


