/*
Alephium API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.5.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alephium

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MemPooled type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MemPooled{}

// MemPooled struct for MemPooled
type MemPooled struct {
	Type string `json:"type"`
}

type _MemPooled MemPooled

// NewMemPooled instantiates a new MemPooled object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMemPooled(type_ string) *MemPooled {
	this := MemPooled{}
	this.Type = type_
	return &this
}

// NewMemPooledWithDefaults instantiates a new MemPooled object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMemPooledWithDefaults() *MemPooled {
	this := MemPooled{}
	return &this
}

// GetType returns the Type field value
func (o *MemPooled) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *MemPooled) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *MemPooled) SetType(v string) {
	o.Type = v
}

func (o MemPooled) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MemPooled) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *MemPooled) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMemPooled := _MemPooled{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMemPooled)

	if err != nil {
		return err
	}

	*o = MemPooled(varMemPooled)

	return err
}

type NullableMemPooled struct {
	value *MemPooled
	isSet bool
}

func (v NullableMemPooled) Get() *MemPooled {
	return v.value
}

func (v *NullableMemPooled) Set(val *MemPooled) {
	v.value = val
	v.isSet = true
}

func (v NullableMemPooled) IsSet() bool {
	return v.isSet
}

func (v *NullableMemPooled) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMemPooled(val *MemPooled) *NullableMemPooled {
	return &NullableMemPooled{value: val, isSet: true}
}

func (v NullableMemPooled) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMemPooled) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


