/*
Alephium API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.7.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package alephium

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RichBlockEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RichBlockEntry{}

// RichBlockEntry struct for RichBlockEntry
type RichBlockEntry struct {
	Hash string `json:"hash"`
	Timestamp int64 `json:"timestamp"`
	ChainFrom int32 `json:"chainFrom"`
	ChainTo int32 `json:"chainTo"`
	Height int32 `json:"height"`
	Deps []string `json:"deps"`
	Transactions []RichTransaction `json:"transactions"`
	Nonce string `json:"nonce"`
	Version int32 `json:"version"`
	DepStateHash string `json:"depStateHash"`
	TxsHash string `json:"txsHash"`
	Target string `json:"target"`
	GhostUncles []GhostUncleBlockEntry `json:"ghostUncles"`
	ConflictedTxs []string `json:"conflictedTxs,omitempty"`
}

type _RichBlockEntry RichBlockEntry

// NewRichBlockEntry instantiates a new RichBlockEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRichBlockEntry(hash string, timestamp int64, chainFrom int32, chainTo int32, height int32, deps []string, transactions []RichTransaction, nonce string, version int32, depStateHash string, txsHash string, target string, ghostUncles []GhostUncleBlockEntry) *RichBlockEntry {
	this := RichBlockEntry{}
	this.Hash = hash
	this.Timestamp = timestamp
	this.ChainFrom = chainFrom
	this.ChainTo = chainTo
	this.Height = height
	this.Deps = deps
	this.Transactions = transactions
	this.Nonce = nonce
	this.Version = version
	this.DepStateHash = depStateHash
	this.TxsHash = txsHash
	this.Target = target
	this.GhostUncles = ghostUncles
	return &this
}

// NewRichBlockEntryWithDefaults instantiates a new RichBlockEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRichBlockEntryWithDefaults() *RichBlockEntry {
	this := RichBlockEntry{}
	return &this
}

// GetHash returns the Hash field value
func (o *RichBlockEntry) GetHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Hash
}

// GetHashOk returns a tuple with the Hash field value
// and a boolean to check if the value has been set.
func (o *RichBlockEntry) GetHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Hash, true
}

// SetHash sets field value
func (o *RichBlockEntry) SetHash(v string) {
	o.Hash = v
}

// GetTimestamp returns the Timestamp field value
func (o *RichBlockEntry) GetTimestamp() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *RichBlockEntry) GetTimestampOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *RichBlockEntry) SetTimestamp(v int64) {
	o.Timestamp = v
}

// GetChainFrom returns the ChainFrom field value
func (o *RichBlockEntry) GetChainFrom() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ChainFrom
}

// GetChainFromOk returns a tuple with the ChainFrom field value
// and a boolean to check if the value has been set.
func (o *RichBlockEntry) GetChainFromOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChainFrom, true
}

// SetChainFrom sets field value
func (o *RichBlockEntry) SetChainFrom(v int32) {
	o.ChainFrom = v
}

// GetChainTo returns the ChainTo field value
func (o *RichBlockEntry) GetChainTo() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ChainTo
}

// GetChainToOk returns a tuple with the ChainTo field value
// and a boolean to check if the value has been set.
func (o *RichBlockEntry) GetChainToOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChainTo, true
}

// SetChainTo sets field value
func (o *RichBlockEntry) SetChainTo(v int32) {
	o.ChainTo = v
}

// GetHeight returns the Height field value
func (o *RichBlockEntry) GetHeight() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Height
}

// GetHeightOk returns a tuple with the Height field value
// and a boolean to check if the value has been set.
func (o *RichBlockEntry) GetHeightOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Height, true
}

// SetHeight sets field value
func (o *RichBlockEntry) SetHeight(v int32) {
	o.Height = v
}

// GetDeps returns the Deps field value
func (o *RichBlockEntry) GetDeps() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Deps
}

// GetDepsOk returns a tuple with the Deps field value
// and a boolean to check if the value has been set.
func (o *RichBlockEntry) GetDepsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Deps, true
}

// SetDeps sets field value
func (o *RichBlockEntry) SetDeps(v []string) {
	o.Deps = v
}

// GetTransactions returns the Transactions field value
func (o *RichBlockEntry) GetTransactions() []RichTransaction {
	if o == nil {
		var ret []RichTransaction
		return ret
	}

	return o.Transactions
}

// GetTransactionsOk returns a tuple with the Transactions field value
// and a boolean to check if the value has been set.
func (o *RichBlockEntry) GetTransactionsOk() ([]RichTransaction, bool) {
	if o == nil {
		return nil, false
	}
	return o.Transactions, true
}

// SetTransactions sets field value
func (o *RichBlockEntry) SetTransactions(v []RichTransaction) {
	o.Transactions = v
}

// GetNonce returns the Nonce field value
func (o *RichBlockEntry) GetNonce() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Nonce
}

// GetNonceOk returns a tuple with the Nonce field value
// and a boolean to check if the value has been set.
func (o *RichBlockEntry) GetNonceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Nonce, true
}

// SetNonce sets field value
func (o *RichBlockEntry) SetNonce(v string) {
	o.Nonce = v
}

// GetVersion returns the Version field value
func (o *RichBlockEntry) GetVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *RichBlockEntry) GetVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *RichBlockEntry) SetVersion(v int32) {
	o.Version = v
}

// GetDepStateHash returns the DepStateHash field value
func (o *RichBlockEntry) GetDepStateHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DepStateHash
}

// GetDepStateHashOk returns a tuple with the DepStateHash field value
// and a boolean to check if the value has been set.
func (o *RichBlockEntry) GetDepStateHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DepStateHash, true
}

// SetDepStateHash sets field value
func (o *RichBlockEntry) SetDepStateHash(v string) {
	o.DepStateHash = v
}

// GetTxsHash returns the TxsHash field value
func (o *RichBlockEntry) GetTxsHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TxsHash
}

// GetTxsHashOk returns a tuple with the TxsHash field value
// and a boolean to check if the value has been set.
func (o *RichBlockEntry) GetTxsHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TxsHash, true
}

// SetTxsHash sets field value
func (o *RichBlockEntry) SetTxsHash(v string) {
	o.TxsHash = v
}

// GetTarget returns the Target field value
func (o *RichBlockEntry) GetTarget() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Target
}

// GetTargetOk returns a tuple with the Target field value
// and a boolean to check if the value has been set.
func (o *RichBlockEntry) GetTargetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Target, true
}

// SetTarget sets field value
func (o *RichBlockEntry) SetTarget(v string) {
	o.Target = v
}

// GetGhostUncles returns the GhostUncles field value
func (o *RichBlockEntry) GetGhostUncles() []GhostUncleBlockEntry {
	if o == nil {
		var ret []GhostUncleBlockEntry
		return ret
	}

	return o.GhostUncles
}

// GetGhostUnclesOk returns a tuple with the GhostUncles field value
// and a boolean to check if the value has been set.
func (o *RichBlockEntry) GetGhostUnclesOk() ([]GhostUncleBlockEntry, bool) {
	if o == nil {
		return nil, false
	}
	return o.GhostUncles, true
}

// SetGhostUncles sets field value
func (o *RichBlockEntry) SetGhostUncles(v []GhostUncleBlockEntry) {
	o.GhostUncles = v
}

// GetConflictedTxs returns the ConflictedTxs field value if set, zero value otherwise.
func (o *RichBlockEntry) GetConflictedTxs() []string {
	if o == nil || IsNil(o.ConflictedTxs) {
		var ret []string
		return ret
	}
	return o.ConflictedTxs
}

// GetConflictedTxsOk returns a tuple with the ConflictedTxs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RichBlockEntry) GetConflictedTxsOk() ([]string, bool) {
	if o == nil || IsNil(o.ConflictedTxs) {
		return nil, false
	}
	return o.ConflictedTxs, true
}

// HasConflictedTxs returns a boolean if a field has been set.
func (o *RichBlockEntry) HasConflictedTxs() bool {
	if o != nil && !IsNil(o.ConflictedTxs) {
		return true
	}

	return false
}

// SetConflictedTxs gets a reference to the given []string and assigns it to the ConflictedTxs field.
func (o *RichBlockEntry) SetConflictedTxs(v []string) {
	o.ConflictedTxs = v
}

func (o RichBlockEntry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RichBlockEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["hash"] = o.Hash
	toSerialize["timestamp"] = o.Timestamp
	toSerialize["chainFrom"] = o.ChainFrom
	toSerialize["chainTo"] = o.ChainTo
	toSerialize["height"] = o.Height
	toSerialize["deps"] = o.Deps
	toSerialize["transactions"] = o.Transactions
	toSerialize["nonce"] = o.Nonce
	toSerialize["version"] = o.Version
	toSerialize["depStateHash"] = o.DepStateHash
	toSerialize["txsHash"] = o.TxsHash
	toSerialize["target"] = o.Target
	toSerialize["ghostUncles"] = o.GhostUncles
	if !IsNil(o.ConflictedTxs) {
		toSerialize["conflictedTxs"] = o.ConflictedTxs
	}
	return toSerialize, nil
}

func (o *RichBlockEntry) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"hash",
		"timestamp",
		"chainFrom",
		"chainTo",
		"height",
		"deps",
		"transactions",
		"nonce",
		"version",
		"depStateHash",
		"txsHash",
		"target",
		"ghostUncles",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRichBlockEntry := _RichBlockEntry{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRichBlockEntry)

	if err != nil {
		return err
	}

	*o = RichBlockEntry(varRichBlockEntry)

	return err
}

type NullableRichBlockEntry struct {
	value *RichBlockEntry
	isSet bool
}

func (v NullableRichBlockEntry) Get() *RichBlockEntry {
	return v.value
}

func (v *NullableRichBlockEntry) Set(val *RichBlockEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableRichBlockEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableRichBlockEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRichBlockEntry(val *RichBlockEntry) *NullableRichBlockEntry {
	return &NullableRichBlockEntry{value: val, isSet: true}
}

func (v NullableRichBlockEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRichBlockEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


