name: Test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18.6'
      - run: go build -v ./... && go test -v ./...

